// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCejE4ba8nkka3yZdr_06KirWHr_bPBMkM',
    appId: '1:530914251911:web:4fbf839aaaddf055571422',
    messagingSenderId: '530914251911',
    projectId: 'chattapp-41c74',
    authDomain: 'chattapp-41c74.firebaseapp.com',
    storageBucket: 'chattapp-41c74.appspot.com',
    measurementId: 'G-QKMHD9JJT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtke6G0QSCHU_7qS9wHyhOJ_3xhHHaYOM',
    appId: '1:530914251911:android:91a69f897afcb1a6571422',
    messagingSenderId: '530914251911',
    projectId: 'chattapp-41c74',
    storageBucket: 'chattapp-41c74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPI5CQ0WlRoHXyKqQRMg5HJ_HQHeypI8k',
    appId: '1:530914251911:ios:bf3cc3640f89f377571422',
    messagingSenderId: '530914251911',
    projectId: 'chattapp-41c74',
    storageBucket: 'chattapp-41c74.appspot.com',
    iosClientId: '530914251911-b2qaa68996s7hfgov8kqnjb22q3vn266.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPI5CQ0WlRoHXyKqQRMg5HJ_HQHeypI8k',
    appId: '1:530914251911:ios:bf3cc3640f89f377571422',
    messagingSenderId: '530914251911',
    projectId: 'chattapp-41c74',
    storageBucket: 'chattapp-41c74.appspot.com',
    iosClientId: '530914251911-b2qaa68996s7hfgov8kqnjb22q3vn266.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
